# All Shopia Upptime Configuration
owner: Hikarai
repo: status-page

sites:
  - name: All Shopia Store
    url: https://www.allshopia.com
    icon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
    description: "Main store homepage"
    expectedStatusCodes: [200]

  # Critical Shopping Journey Pages (Customer Funnel)
  - name: Product Pages
    url: https://allshopia.com/collections/all
    description: "Product listing and detail pages"
    maxResponseTime: 3000
    expectedStatusCodes: [200]
    
  - name: Shopping Cart
    url: https://allshopia.com/cart
    description: "Customer shopping cart"
    maxResponseTime: 3000
    expectedStatusCodes: [200]
  
  - name: Checkout Process
    url: https://allshopia.com/checkout
    description: "Checkout and payment gateway"
    maxResponseTime: 4000
    expectedStatusCodes: [200]
    # Warning: Use this cautiously. If the page text changes, it will cause false alarms.
    # __dangerous__body_down_if_text_missing: '"Checkout"'
  
  # Content & Support Pages
  - name: Customer Support
    url: https://allshopia.com/pages/contact-us
    description: "Contact and support pages"
    expectedStatusCodes: [200]

# Monitoring Settings
checkInterval: 5
delay: 3000 # 3-second delay between checks
maxResponseTime: 5000 # 5 seconds threshold for "degraded" performance
timezone: "Asia/Karachi"

# Status Page Branding & Setup
status-website:
  # CRITICAL FIX: This line makes CSS load correctly on GitHub Pages
  baseUrl: /status-page
  cname: status.allshopia.com
  name: All Shopia Status
  # Use a valid logo URL from your store
  logoUrl: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/logo_800x800_0fc25045-3739-4812-a74d-a8186edf1954.png?v=1764260129
  
  introTitle: "All Shopia System Status"
  introMessage: "Welcome to our live status page. Here you can see the real-time availability and performance of our online store. This page is updated automatically every 5 minutes."
  
  navbar:
    - title: Status Home
      href: /
    - title: Visit Our Store
      href: https://www.allshopia.com
    - title: Report History
      href: /history
    - title: GitHub
      href: https://github.com/Hikarai/status-page
  
  favicon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066

# THEME CONFIGURATION (Corrected Structure)
# The 'theme:' key should be under 'status-website:' per the docs.
status-website:
  theme:
    primaryColor: "#1F2937"
    secondaryColor: "#3B82F6"
    backgroundColor: "#F9FAFB"
  # Alternatively, you can just use a built-in theme:
  # theme: light

# Notifications
notifications:
  - type: email

# Assignees & Issue Settings (Optional)
assignees: [Hikarai]
skipDeleteIssues: false
