# Change these first
owner: Hikarai # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

# Core Settings
timezone: "Asia/Karachi"

sites:
  - name: AllShopia Home
    url: https://www.allshopia.com
    icon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
    maxResponseTime: 5000
    expectedStatusCodes: [200]
  - name: Product Collection
    url: https://www.allshopia.com/collections/all
    icon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
    maxResponseTime: 5000
    expectedStatusCodes: [200]
  - name: Shopping Cart
    url: https://www.allshopia.com/cart
    icon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
    maxResponseTime: 3000 # Stricter threshold for interactive pages
    expectedStatusCodes: [200]

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.allshopia.com
  baseUrl: /status-page  # UNCOMMENTED: Required for assets to load correctly
  logoUrl: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
  name: All Shopia Status
  introTitle: "**All Shopia** Service Status"
  introMessage: Welcome to the All Shopia Status Page. We proactively monitor the health and performance of our core storefront pages to ensure a seamless shopping experience for our customers.
  navbar:
    - title: Status
      href: /
    - title: Visit Store
      href: https://www.allshopia.com
    - title: GitHub
      href: https://github.com/Hikarai/status-page
  favicon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
  # Custom CSS to fix mobile graph sizing
  customCSS: |
    /* Make graphs responsive on smaller screens */
    @media screen and (max-width: 768px) {
      .graph img {
        max-width: 100%;
        height: auto;
      }
    }

# Workflow Schedule
# Keep in mind that a scheduled GitHub Action cannot run faster than every 5 minutes.
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * 0" # Runs weekly on Sunday
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
