# All Shopia Upptime Configuration
owner: Hikarai
repo: status-page

sites:
  - name: AllShopia Home
    url: https://www.allshopia.com
    # Optional: You can add a custom icon for each site. For example:
    # icon: https://www.allshopia.com/favicon.ico
  - name: Product Collection
    url: https://www.allshopia.com/collections/all
  - name: Shopping Cart
    url: https://www.allshopia.com/cart

# Status website settings (CRITICAL: baseUrl fixes CSS loading)
status-website:
  baseUrl: /status-page # Required for GitHub Pages
  cname: status.allshopia.com # Your custom domain
  name: All Shopia Status
  # Using your provided URL for both logo and favicon
  logoUrl: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
  favicon: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/cropped_circle_logo.png?v=1759408066
