# All Shopia Upptime Configuration
owner: Hikarai
repo: status-page # Use the EXACT name of your GitHub repository

sites:
  - name: All Shopia Store
    url: https://www.allshopia.com
    description: "The primary online store"

# Monitoring Settings
checkInterval: 5 # Check every 5 minutes
maxResponseTime: 10000 # Alert if slower than 10 seconds
timezone: "Asia/Karachi" # Set to Pakistan time

# Status Page Branding & Setup
status-website:
  cname: status.allshopia.com # Your custom domain
  name: All Shopia Status
  logoUrl: https://cdn.shopify.com/s/files/1/0947/3117/4253/files/logo_800x800_0fc25045-3739-4812-a74d-a8186edf1954.png?v=1764260129
  introTitle: "All Shopia System Status"
  introMessage: "Welcome to our official status page. Here you can see the real-time performance and availability of our online store and services. This page is updated automatically."
  navbar:
    - title: Status Home
      href: /
    - title: Visit Our Store
      href: https://www.allshopia.com
    - title: View on GitHub
      href: https://github.com/Hikarai/status-page

# Page Theme (Clean & Professional)
theme:
  primaryColor: "#1F2937" # Dark gray
  secondaryColor: "#3B82F6" # Blue accent
  backgroundColor: "#F9FAFB" # Light background
  darkMode: false
